# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
modLoader="javafml"
loaderVersion="[51,)"
license="MIT license"
issueTrackerURL="https://github.com/minhnh303/Thirst-Mod/issues"
[[mods]]
modId="thirst"
version="${file.jarVersion}"
displayName="Yet Another Thirst"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/minhnh303/Thirst-Mod"
logoFile="yetanotherthirst.png"
credits="Thanks to ghen-git and mlus-asuka for the original code."
authors="MinhNH"
description='''
Modern take on the thirst-bar mechanic, compatible with a lot of contemporary mods
'''
[[dependencies.thirst]]
    modId="forge"
    mandatory=true
    versionRange="[51.0.33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thirst]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thirst]]
    modId="create"
    mandatory=false
    versionRange="[0.5.1.a,)"
    ordering="NONE"
    side="BOTH"
